# Generated by Django 4.1.3 on 2022-11-19 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_foodprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodprofile',
            name='food',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='food.fooditem'),
        ),
    ]
