# Generated by Django 4.1.3 on 2022-11-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_foodprofile_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('desc', models.TextField(blank=True)),
            ],
        ),
    ]
