# Generated by Django 4.1.3 on 2022-11-19 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_foodkind'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='kind',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='fooditem', to='food.foodkind'),
            preserve_default=False,
        ),
    ]
