# Generated by Django 4.1.3 on 2022-11-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_fooditem_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTypeMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Meal',
            },
        ),
        migrations.AddField(
            model_name='fooditem',
            name='meal',
            field=models.ManyToManyField(related_name='food', to='food.foodtypemeal'),
        ),
    ]
